baseURL = "http://ampersandsoftworks.com/"
languageCode = "en-us"
title = "Ampersand Softworks"
enableInlineShortcodes = true

theme = "soho"
summarylength = 20
enableEmoji = true

googleAnalytics = "UA-3840385-15"

[params]
author = "brett ohland"
description = "A development blog for pocket computer software and DIY keyboards"

#gravatar = "hello@brettohland.com"
profilePicture = "images/headshot.jpg"

copyright = "brett ohland"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

themeColor = "#FF1A87"

customCss = ["css/custom.css"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/brettohland/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/brettohland"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
