source 'https://rubygems.org'
gem 'bundler'
gem 'webrick'
gem 'jekyll'

gem 'jekyll-compose'
gem 'jekyll-feed'
gem 'jekyll-figure'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-tagging'
gem 'jekyll-themes-control'
gem 'jekyll-tidy'
